export default {
    GET_POSTS:"GET_POSTS",
    GET_POST_BY_ID:"GET_POST_BY_ID",
    CREATE_POST:"CREATE_POST",
    UPDATE_POST:"UPDATE_POST",
    LIKE_POST:"LIKE_POST",
    DELETE_POST:"DELETE_POST",
    START_LOADING_POSTS:"START_LOADING_POSTS",
    END_LOADING_POSTS:"END_LOADING_POSTS",
    SIGNIN:"SIGNIN",
    SIGNUP:"SIGNUP",
    LOGOUT:"LOGOUT",
    CREATE_USER_ACCOUNT:"CREATE_USER_ACCOUNT"
}