export default {
    GET_POSTS:"GET_POSTS",
    CREATE_POST:"CREATE_POST",
    UPDATE_POST:"UPDATE_POST",
    LIKE_POST:"LIKE_POST",
    DELETE_POST:"DELETE_POST",
    SIGNIN:"SIGNIN",
    SIGNUP:"SIGNUP",
    LOGOUT:"LOGOUT"
}