export const dataProducts = [
  {
    category: 'pralnice',
    title: 'Pralnice przemysłowe',
    short_title: 'Pralnice',
    desc: '',
    pathname: 'pralnice',
    kind: [
      {
        title: 'Pralnice bębnowe o załadunku czołowym',
        subtitle: 'przemysłowe urządzenia pralnicze bez wirowania, załadunek 8 - 22 kg',
        control_options: [1, 2],
        purpose: ['pranie', 'płukanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#czolowe-pb',
        images: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-586x784'],
        thumbnails: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-100x100'],
        features: ['trwała budowa', 'oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterownik mikroprocesorowy'],
        options: ['różne podgrzewy', 'oblachowanie ze stali kwasoodpornej', 'farbiarka', 'dekatyzacja dzinsu'],
        label: 'załadaunek czołowy - PB',
      },
      {
        title: 'Pralnice bębnowe o załadunku czołowym',
        subtitle: 'przemysłowe urządzenia pralnicze bez wirowania, załadunek 30 - 50 kg',
        control_options: [1, 2],
        purpose: ['pranie', 'płukanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#czolowe-pc',
        images: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-586x784'],
        thumbnails: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-100x100'],
        features: ['trwała budowa', 'oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterownik mikroprocesorowy'],
        options: ['różne podgrzewy', 'oblachowanie ze stali kwasoodpornej', 'farbiarka', 'dekatyzacja dzinsu'],
        label: 'załadunek czołowy - PC',
      },
      {
        title: 'Pralnice bębnowe o załadunku bocznym',
        subtitle: 'przemysłowe urządzenia pralnicze bez wirowania, załadunek 30 -50 kg',
        control_options: [1],
        purpose: ['pranie', 'płukanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#boczne',
        images: [],
        thumbnails: [],
        features: ['trwała budowa', 'oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterownik mikroprocesorowy'],
        options: ['różne podgrzewy', 'oblachowanie ze stali kwasoodpornej', 'farbiarka', 'dekatyzacja dzinsu'],
        label: 'załadunek boczny - PB',
      },
      {
        title: 'Specjalistyczne pralnice bębnowe o załadunku czołowym',
        subtitle: 'przemysłowe urządzenia pralnicze, załadunek 90 - 120 kg',
        control_options: [1, 2, 16],
        purpose: ['pranie', 'płukanie', 'farbowanie', 'dekatyzacja'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła', 'parowy pośredni'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#specjalne-czolowe',
        images: [],
        thumbnails: [],
        features: ['oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterowanie według określonych potrzeb'],
        options: ['podgrzew parowy bezpośredni lub pośredni', 'oblachowanie ze stali kwasoodpornej', 'lekkie podwirowanie'],
        label: 'specjalistyczne, czołowe - PC',
      },
      {
        title: 'Specjalistyczne pralnice bębnowe o załadunku bocznym',
        subtitle: 'przemysłowe urządzenia pralnicze, załadunek 200 - 300 kg',
        control_options: [1, 2, 16],
        purpose: ['pranie', 'płukanie', 'farbowanie', 'dekatyzacja'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła', 'parowy pośredni'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#specjalne-boczne',
        images: [],
        thumbnails: [],
        features: ['oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterowanie według określonych potrzeb'],
        options: ['podgrzew parowy bezpośredni lub pośredni', 'oblachowanie ze stali kwasoodpornej', 'lekkie podwirowanie'],
        label: 'specjalistyczne, boczne - PB',
      },
    ],
  },
  {
    category: 'pralnicowirówki',
    title: 'Pralnicowirówki przemysłowe',
    short_title: 'Pralnicowirówki',
    desc: '',
    pathname: 'pralnicowirowki',
    kind: [
      {
        title: 'Pralnicowirówki normalnoobrotowe, Pralma',
        subtitle: 'przemysłowe pralnicowirówki sztywnomocowane, załadunek 10 - 22 kg',
        control_options: [2],
        purpose: ['pranie', 'płukanie', 'wirowanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '200',
        mount: 'tak',
        pathname: 'pralnicowirowki#normalnoobrotowe-pralma',
        images: [],
        thumbnails: [],
        features: ['oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'wymaga specjalnego fundamentu', 'napęd z przemiennikiem częstotliwości', 'elektrozawór parowy w standardzie (dla wersji parowej)', 'sterownik mikroprocesorowy'],
        options: ['wersja MOP'],
        label: 'normalnoobrotowe - Pralma',
      },
      {
        title: 'Pralnicowirówki normalnoobrotowe, RX',
        subtitle: 'przemysłowe pralnicowirówki sztywnomocowane, załadunek 8 - 52 kg',
        control_options: [3],
        purpose: ['pranie', 'płukanie', 'wirowanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno z przystosowaniem do pary', 'woda ciepła'],
        g_factor: '100-150',
        mount: 'tak',
        pathname: 'pralnicowirowki#normalnoobrotowe-rx',
        images: [],
        thumbnails: [],
        features: ['mocowane do podłoża', 'panel górny ze stali nierdzewnej', 'bęben wewnętrzny i zewnętrzny ze stali nierdzewnej', 'łatwy w użyciu programator', 'duży zawór odpływowy - 76 mm', 'łatwy dostęp do wszystkich podzespołów', 'duże drzwi wsadowe ułatwiające załadunek i rozładunek'],
        options: ['panele górne i boczne ze stali nierdzewnej', 'wtyczka USB w panelu tylnym', 'podłączenie do pomp płynnych środków piorących', 'zestaw odzyskiwania wody', 'trzeci wlot wody'],
        label: 'normalnoobrotowe - RX',
      },
      {
        title: 'Pralnicowirówki szybkoobrotowe, RX',
        subtitle: 'przemysłowe pralnicowirówki sztywnomocowane, załadunek 8 - 28 kg',
        control_options: [3],
        purpose: ['pranie', 'płukanie', 'wirowanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno z przystosowaniem do pary', 'woda ciepła'],
        g_factor: '200',
        mount: 'tak',
        pathname: 'pralnicowirowki#szybkoobrotowe-rx',
        images: [],
        thumbnails: [],
        features: ['mocowane do podłoża', 'panel górny ze stali nierdzewnej', 'bęben wewnętrzny i zewnętrzny ze stali nierdzewnej', 'łatwy w użyciu programator', 'duży zawór odpływowy - 76 mm', 'łatwy dostęp do wszystkich podzespołów', 'duże drzwi wsadowe ułatwiające załadunek i rozładunek'],
        options: ['panele górne i boczne ze stali nierdzewnej', 'wtyczka USB w panelu tylnym', 'podłączenie do pomp płynnych środków piorących', 'zestaw odzyskiwania wody', 'trzeci wlot wody'],
        label: 'szybkoobrotowe - RX',
      },
    ],
  },
];
