export const dataProducts = [
  {
    category: 'pralnice',
    title: 'Pralnice przemysłowe',
    short_title: 'Pralnice',
    desc: '',
    pathname: 'pralnice',
    kind: [
      {
        title: 'Pralnice bębnowe o załadunku czołowym 8 - 22 kg',
        subtitle: '',
        control_options: [1, 2],
        purpose: ['pranie', 'płukanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#czolowe-pb',
        images: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-586x784'],
        thumbnails: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-100x100'],
        features: ['trwała budowa', 'oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterownik mikroprocesorowy'],
        options: ['różne podgrzewy', 'oblachowanie ze stali kwasoodpornej', 'farbiarka', 'dekatyzacja dzinsu'],
        parameters: [
          { id: 1, name: 'typ', unit: '-', values: ['PBE-08', 'PBE-08A', 'PBE-15', 'PBE-15A', 'PBE-22', 'PBE-22A', 'PBP-08', 'PBP-08A', 'PBP-15', 'PBP-15A', 'PBP-22', 'PBP-22A'] },
          { id: 2, name: 'ładowność 1:10', unit: 'kg', values: ['8', '8', '15', '15', '22', '22', '8', '8', '15', '15', '22', '22'] },
          { id: 3, name: 'pojemność bębna', unit: 'dm3', values: ['80', '80', '150', '150', '220', '220', '80', '80', '150', '150', '220', '220'] },
          { id: 4, name: 'moc podgrzewu elektrycznego', unit: 'kW', values: ['12', '12', '18', '18', '18', '18', '-', '-', '-', '-', '-', '-'] },
          { id: 5, name: 'moc zainstalowana', unit: 'kW', values: ['12.55', '12.55', '18.55', '18.55', '18.55', '18.55', '0.55', '0.55', '0.55', '0.55', '0.55', '0.55'] },
          { id: 6, name: 'podgrzew ciepłą wodą', unit: 'C', values: ['90'] },
          { id: 7, name: 'ciśnienie wody', unit: 'kPa', values: ['100-800'] },
          { id: 8, name: 'poziom hałasu', unit: 'dB(A)', values: ['<6 5'] },
          { id: 9, name: 'średnica zaworu spustowego', unit: 'cal', values: ['2.5', '3', '2.5', '3', '2.5', '3', '2.5', '3', '2.5', '3', '2.5', '3'] },
          { id: 10, name: 'średnica zaworu wody', unit: 'cal', values: ['3/4'] },
          { id: 11, name: 'podłączenie pary', unit: 'cal', values: ['1/2'] },
          { id: 12, name: 'ciśnienie pary', unit: 'kPa', values: ['100-800'] },
          { id: 13, name: 'zasilanie', unit: '-', values: ['3x380-415V + PEN / 50Hz'] },
          { id: 14, name: 'wysokość', unit: 'mm', values: ['1250'] },
          { id: 15, name: 'szerokość', unit: 'mm', values: ['880'] },
          { id: 16, name: 'głębokość', unit: 'mm', values: ['650', '650', '880', '880', '980', '980', '650', '650', '880', '880', '980', '980'] },
          { id: 17, name: 'masa netto', unit: 'kg', values: ['200', '200', '210', '210', '210', '210', '200', '200', '210', '210', '210', '210'] },
        ],
        label: 'załadaunek czołowy - PB',
      },
      {
        title: 'Pralnice bębnowe o załadunku czołowym 30 - 50 kg',
        subtitle: '',
        control_options: [1, 2],
        purpose: ['pranie', 'płukanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#czolowe-pc',
        images: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-586x784', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-586x784'],
        thumbnails: ['pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-1-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-2-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-3-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-4-100x100', 'pralnica-bebnowa-o-zaladunku-czolowym-8-22-slider-5-100x100'],
        features: ['trwała budowa', 'oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterownik mikroprocesorowy'],
        options: ['różne podgrzewy', 'oblachowanie ze stali kwasoodpornej', 'farbiarka', 'dekatyzacja dzinsu'],
        parameters: [
          { id: 1, name: 'typ', unit: '-', values: ['PCE-30', 'PCE-30A', 'PCE-50', 'PCE-50A', 'PCP-30', 'PCP-30A', 'PCP-50', 'PCP-50A'] },
          { id: 2, name: 'ładowność 1:10', unit: 'kg', values: ['30', '30', '50', '50', '30', '30', '50', '50'] },
          { id: 3, name: 'pojemność bębna', unit: 'dm3', values: ['300', '300', '500', '500', '300', '300', '500', '500'] },
          { id: 4, name: 'moc podgrzewu elektrycznego', unit: 'kW', values: ['27', '27', '27/36', '27/36', '27', '27', '27/36', '27/36'] },
          { id: 5, name: 'moc zainstalowana', unit: 'kW', values: ['28.7', '28.7', '28.7/37.7', '28.7/37.7', '1.7', '1.7', '1.7', '1.7'] },
          { id: 6, name: 'podgrzew ciepłą wodą', unit: 'C', values: ['90'] },
          { id: 7, name: 'ciśnienie wody', unit: 'kPa', values: ['100-800'] },
          { id: 8, name: 'poziom hałasu', unit: 'dB(A)', values: ['< 6 5'] },
          { id: 9, name: 'średnica zaworu spustowego', unit: 'cal', values: ['3'] },
          { id: 10, name: 'średnica zaworu wody', unit: 'cal', values: ['3/4'] },
          { id: 11, name: 'podłączenie pary', unit: 'cal', values: ['1/2'] },
          { id: 12, name: 'ciśnienie pary', unit: 'kPa', values: ['100-800'] },
          { id: 13, name: 'zasilanie', unit: '-', values: ['3x380-415V + PEN / 50Hz'] },
          { id: 14, name: 'wysokość', unit: 'mm', values: ['1400'] },
          { id: 15, name: 'szerokość', unit: 'mm', values: ['1050'] },
          { id: 16, name: 'głębokość', unit: 'mm', values: ['1000', '1000', '1200', '1200', '1000', '1000', '1200', '1200'] },
          { id: 17, name: 'masa netto', unit: 'kg', values: ['400', '400', '415', '415', '400', '400', '415', '415'] },
        ],
        label: 'załadunek czołowy - PC',
      },
      {
        title: 'Pralnice bębnowe o załadunku bocznym 30 - 50 kg',
        subtitle: '',
        control_options: [1],
        purpose: ['pranie', 'płukanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#boczne',
        images: [],
        thumbnails: [],
        features: ['trwała budowa', 'oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterownik mikroprocesorowy'],
        options: ['różne podgrzewy', 'oblachowanie ze stali kwasoodpornej', 'farbiarka', 'dekatyzacja dzinsu'],
        parameters: [],
        label: 'załadunek boczny - PB',
      },
      {
        title: 'Specjalistyczne pralnice bębnowe o załadunku czołowym 90 - 120 kg',
        subtitle: '',
        control_options: [1, 2, 16],
        purpose: ['pranie', 'płukanie', 'farbowanie', 'dekatyzacja'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła', 'parowy pośredni'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#specjalne-czolowe',
        images: [],
        thumbnails: [],
        features: ['oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterowanie według określonych potrzeb'],
        options: ['podgrzew parowy bezpośredni lub pośredni', 'oblachowanie ze stali kwasoodpornej', 'lekkie podwirowanie'],
        parameters: [],
        label: 'specjalistyczne, czołowe - PC',
      },
      {
        title: 'Specjalistyczne pralnice bębnowe o załadunku bocznym 200 - 300 kg',
        subtitle: '',
        control_options: [1, 2, 16],
        purpose: ['pranie', 'płukanie', 'farbowanie', 'dekatyzacja'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła', 'parowy pośredni'],
        g_factor: '',
        mount: '',
        pathname: 'pralnice#specjalne-boczne',
        images: [],
        thumbnails: [],
        features: ['oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'prosta konstrukcja', 'niskie koszty eksploatacji i serwisu', 'sterowanie według określonych potrzeb'],
        options: ['podgrzew parowy bezpośredni lub pośredni', 'oblachowanie ze stali kwasoodpornej', 'lekkie podwirowanie'],
        parameters: [],
        label: 'specjalistyczne, boczne - PB',
      },
    ],
  },
  {
    category: 'pralnicowirówki',
    title: 'Pralnicowirówki przemysłowe',
    short_title: 'Pralnicowirówki',
    desc: '',
    pathname: 'pralnicowirowki',
    kind: [
      {
        title: 'Pralnicowirówki normalnoobrotowe, Pralma',
        subtitle: 'przemysłowe pralnicowirówki sztywnomocowane, załadunek 10 - 22 kg',
        control_options: [2],
        purpose: ['pranie', 'płukanie', 'wirowanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno - parowy', 'woda ciepła'],
        g_factor: '200',
        mount: 'tak',
        pathname: 'pralnicowirowki#normalnoobrotowe-pralma',
        images: [],
        thumbnails: [],
        features: ['oblachowanie ze stali nierdzewnej', 'oba bębny ze stali nierdzewnej', 'wymaga specjalnego fundamentu', 'napęd z przemiennikiem częstotliwości', 'elektrozawór parowy w standardzie (dla wersji parowej)', 'sterownik mikroprocesorowy'],
        options: ['wersja MOP'],
        parameters: [],
        label: 'normalnoobrotowe - Pralma',
      },
      {
        title: 'Pralnicowirówki normalnoobrotowe, RX',
        subtitle: 'przemysłowe pralnicowirówki sztywnomocowane, załadunek 8 - 52 kg',
        control_options: [3],
        purpose: ['pranie', 'płukanie', 'wirowanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno z przystosowaniem do pary', 'woda ciepła'],
        g_factor: '100-150',
        mount: 'tak',
        pathname: 'pralnicowirowki#normalnoobrotowe-rx',
        images: [],
        thumbnails: [],
        features: ['mocowane do podłoża', 'panel górny ze stali nierdzewnej', 'bęben wewnętrzny i zewnętrzny ze stali nierdzewnej', 'łatwy w użyciu programator', 'duży zawór odpływowy - 76 mm', 'łatwy dostęp do wszystkich podzespołów', 'duże drzwi wsadowe ułatwiające załadunek i rozładunek'],
        options: ['panele górne i boczne ze stali nierdzewnej', 'wtyczka USB w panelu tylnym', 'podłączenie do pomp płynnych środków piorących', 'zestaw odzyskiwania wody', 'trzeci wlot wody'],
        parameters: [
          { id: 1, name: 'typ', unit: '-', values: ['RX80', 'RX105', 'RX135', 'RX180', 'RX240', 'RX280', 'RX350', 'RX520'] },
          { id: 2, name: 'maksymalna ładowność 1:9', unit: 'kg', values: ['9', '12', '15', '20', '27', '32', '37', '58'] },
          { id: 3, name: 'ładowność 1:10', unit: 'kg', values: ['7.5', '10.5', '13.5', '18', '24', '28', '33', '52'] },
          { id: 4, name: 'pojemność bębna', unit: 'dm3', values: ['75', '105', '135', '180', '240', '280', '332', '520'] },
          { id: 5, name: 'średnica bębna', unit: 'mm', values: ['530', '620', '620', '750', '750', '750', '914', '914'] },
          { id: 6, name: 'pranie', unit: 'obr./min.', values: ['50', '46', '46', '42', '42', '42', '38', '38'] },
          { id: 7, name: 'wirowanie', unit: 'obr./min.', values: ['820', '760', '760', '490', '490', '490', '540', '440'] },
          { id: 8, name: 'G-faktor', unit: '-', values: ['200', '200', '200', '100', '100', '100', '150', '100'] },
          { id: 9, name: 'moc podgrzewu elektrycznego', unit: 'kW', values: ['*6/9', '6/*9/12', '9/*12', '*12/18', '18', '18/*21.9', '27', '40.6'] },
          { id: 10, name: 'podgrzew ciepłą wodą', unit: 'C', values: ['90'] },
          { id: 11, name: 'ciśnienie wody', unit: 'kPa', values: ['100-800'] },
          { id: 12, name: 'zwrotne ciśnienie wody', unit: 'bar', values: ['1 - 8'] },
          { id: 13, name: 'poziom hałasu', unit: 'dB(A)', values: ['<6 5'] },
          { id: 14, name: 'średnica zaworu wody', unit: 'cal', values: ['3/4', '3/4', '3/4', '3/4', '3/4', '3/4', '3/4', '1'] },
          { id: 15, name: 'wlot wody', unit: 'litrów/minutę', values: ['20', '20', '20', '20', '20', '20', '66-188', '183-518'] },
          { id: 16, name: 'średnica zaworu wody', unit: 'mm', values: ['76', '76', '76', '76', '76', '76', '2x76', '2x76'] },
          { id: 17, name: 'przepływ z zaworu spustowego', unit: 'litrów/minutę', values: ['210', '210', '210', '210', '210', '210', '2x210', '2x210'] },
          { id: 18, name: 'podłączenie pary', unit: 'cal', values: ['1/2', '1/2', '1/2', '1/2', '1/2', '1/2', '3/4', '3/4'] },
          { id: 19, name: 'podłączenie pary', unit: 'cal', values: ['1/2', '1/2', '1/2', '1/2', '1/2', '1/2', '3/4', '3/4'] },
          { id: 20, name: 'ciśnienie pary', unit: 'kPa', values: ['100-800'] },
          { id: 21, name: 'ciśnienie pary', unit: 'kPa', values: ['100-800'] },
          { id: 22, name: 'zasilanie', unit: '-', values: ['200-240/50-60Hz/1Ph (N/A dla podgrzewu elektrycznego)\n,200-240V/50-60Hz/3Ph\n,*380-415V/50-60Hz/3Ph+N\n,380-415V/50-60Hz/3Ph\n,440-480V/50-60Hz/3Ph'] },
          { id: 23, name: 'wysokość', unit: 'mm', values: ['1115', '1225', '1225', '1410', '1410', '1410', '1500', '1500'] },
          { id: 24, name: 'szerokość', unit: 'mm', values: ['660', '750', '750', '890', '890', '890', '1060', '1060'] },
          { id: 25, name: 'głębokość', unit: 'mm', values: ['785', '785', '900', '915', '1060', '1135', '1030', '1315'] },
          { id: 26, name: 'masa netto', unit: 'kg', values: ['135', '170', '190', '255', '275', '290', '410', '520'] },
          { id: 27, name: 'wysokość transportowa', unit: 'mm', values: ['1245', '1355', '1355', '1550', '1550', '1550', '1625', '1625'] },
          { id: 28, name: 'szerokość transportowa', unit: 'mm', values: ['710', '800', '800', '925', '925', '925', '1088', '1088'] },
          { id: 29, name: 'głębokość transportowa', unit: 'mm', values: ['785', '785', '900', '915', '1060', '1135', '1030', '1315'] },
          { id: 30, name: 'masa brutto', unit: 'kg', values: ['145', '185', '200', '270', '290', '305', '425', '535'] },
        ],
        label: 'normalnoobrotowe - RX',
      },
      {
        title: 'Pralnicowirówki szybkoobrotowe, RX',
        subtitle: 'przemysłowe pralnicowirówki sztywnomocowane, załadunek 8 - 28 kg',
        control_options: [3],
        purpose: ['pranie', 'płukanie', 'wirowanie'],
        heating: ['elektryczny', 'parowy bezpośredni', 'eletryczno z przystosowaniem do pary', 'woda ciepła'],
        g_factor: '200',
        mount: 'tak',
        pathname: 'pralnicowirowki#szybkoobrotowe-rx',
        images: [],
        thumbnails: [],
        features: ['mocowane do podłoża', 'panel górny ze stali nierdzewnej', 'bęben wewnętrzny i zewnętrzny ze stali nierdzewnej', 'łatwy w użyciu programator', 'duży zawór odpływowy - 76 mm', 'łatwy dostęp do wszystkich podzespołów', 'duże drzwi wsadowe ułatwiające załadunek i rozładunek'],
        options: ['panele górne i boczne ze stali nierdzewnej', 'wtyczka USB w panelu tylnym', 'podłączenie do pomp płynnych środków piorących', 'zestaw odzyskiwania wody', 'trzeci wlot wody'],
        parameters: [
          { id: 1, name: 'typ', unit: '-', values: ['RX80', 'RX105', 'RX135', 'RX180', 'RX240', 'RX280'] },
          { id: 2, name: 'maksymalna ładowność 1:9', unit: 'kg', values: ['9', '12', '15', '20', '27', '32'] },
          { id: 3, name: 'ładowność 1:10', unit: 'kg', values: ['7.5', '10.5', '13.5', '18', '24', '28'] },
          { id: 4, name: 'pojemność bębna', unit: 'dm3', values: ['75', '105', '135', '180', '240', '280'] },
          { id: 5, name: 'średnica bębna', unit: 'mm', values: ['530', '620', '620', '750', '750', '750'] },
          { id: 6, name: 'pranie', unit: 'obr./min.', values: ['50', '46', '46', '42', '42', '42'] },
          { id: 7, name: 'wirowanie', unit: 'obr./min.', values: ['690'] },
          { id: 8, name: 'G-faktor', unit: '-', values: ['200'] },
          { id: 9, name: 'moc podgrzewu elektrycznego', unit: 'kW', values: ['*6/9', '6/*9/12', '9/*12', '*12/18', '18', '18/*21.9'] },
          { id: 10, name: 'podgrzew ciepłą wodą', unit: 'C', values: ['90'] },
          { id: 11, name: 'ciśnienie wody', unit: 'kPa', values: ['100-800'] },
          { id: 12, name: 'zwrotne ciśnienie wody', unit: 'bar', values: ['1 - 8'] },
          { id: 13, name: 'poziom hałasu', unit: 'dB(A)', values: ['<6 5'] },
          { id: 14, name: 'średnica zaworu wody', unit: 'cal', values: ['3/4'] },
          { id: 15, name: 'wlot wody', unit: 'litrów/minutę', values: ['20'] },
          { id: 16, name: 'średnica zaworu wody', unit: 'mm', values: ['76'] },
          { id: 17, name: 'przepływ z zaworu spustowego', unit: 'litrów/minutę', values: ['210'] },
          { id: 18, name: 'podłączenie pary', unit: 'cal', values: ['1/2'] },
          { id: 19, name: 'podłączenie pary', unit: 'cal', values: ['1/2'] },
          { id: 20, name: 'ciśnienie pary', unit: 'kPa', values: ['100-800'] },
          { id: 21, name: 'ciśnienie pary', unit: 'kPa', values: ['100-800'] },
          { id: 22, name: 'zasilanie', unit: '-', values: ['3x380-415V + PEN / 50Hz'] },
          { id: 23, name: 'wysokość', unit: 'mm', values: ['1115', '1225', '1225', '1410', '1410', '1410'] },
          { id: 24, name: 'szerokość', unit: 'mm', values: ['660', '750', '750', '890', '890', '890'] },
          { id: 25, name: 'głębokość', unit: 'mm', values: ['785', '785', '900', '915', '1060', '1135'] },
          { id: 26, name: 'masa netto', unit: 'kg', values: ['135', '170', '190', '315', '330', '355'] },
          { id: 27, name: 'wysokość transportowa', unit: 'mm', values: ['1245', '1355', '1355', '1550', '1550', '1550'] },
          { id: 28, name: 'szerokość transportowa', unit: 'mm', values: ['710', '800', '800', '925', '925', '925'] },
          { id: 29, name: 'głębokość transportowa', unit: 'mm', values: ['785', '785', '900', '915', '1060', '1135'] },
          { id: 30, name: 'masa brutto', unit: 'kg', values: ['145', '185', '200', '335', '355', '385'] },
        ],
        label: 'szybkoobrotowe - RX',
      },
    ],
  },
];
